module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT", 
    USER_CONNECTED:"USER_CONNECTED", 
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED", 
    MESSAGE_SEND:"MESSAGE_SEND", 
    USER_DISCONNECTED:"USER_DISCONNECTED", 
    TYPING:"TYPING", 
    VERIFY_USER:"VERIFY_USER", 
    LOGOUT:"LOGOUT", 
    DATA_REQ: "DATA_REQ", 
    LOAD_USERS: "LOAD_USERS", 
    SEND_MESSAGE: "SEND_MESSAGE", 
    DATA_REQ: "DATA_REQ", 
    LOAD_MESSAGES: "LOAD_MESSAGES", 
    UPDATE_DB: "UPDATE_DB",
    SEARCH_USER: "SEARCH_USER", 
    ADD_CONTACTS: "ADD_CONTACTS", 
    LOAD_PROFILE: "LOAD_PROFILE"
}